### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by tommydevitt** [btmartin721/extractVariantSites4raxml#2]
When I try to run the script, I get the following error: 

ValueError: not enough values to unpack (expected 2, got 0)

Any suggestions?

**Comment by btmartin721** [comment]
Can you give me the parameters that you used to run the script?

**Comment by btmartin721** [comment]
In other words, can you just copy and paste the command with the arguments that you used to run the script?

**Comment by tommydevitt** [comment]
I tried both ./ascbias.py -p <PHYLIP_INFILE>
and
python3 ./ascbias.py -p <PHYLIP_INFILE>

**Comment by btmartin721** [comment]
OK. Can you send me an example of your phylip file? That way I can try to see what's going on.

**Comment by tommydevitt** [comment]
Just emailed it to you. Thanks for taking a look.

**Comment by btmartin721** [comment]
I couldn't reproduce the error you received when you ran the script. When I ran it on my computer, it didn't produce any errors. However, I suspect it's one of two things. 

First, what operating system are you on? Because I haven't tested this script on Windows. As far as I know it only works on Linux (e.g., Ubuntu) or Unix (MacOSX) based operating systems. 

Second, if you're not on Windows it might be throwing errors because you don't have one or more of the dependencies installed. This script needs numpy, pandas, and biopython to be installed as dependencies.

You can install them in one of two ways: 

1. (recommended): Using Anaconda3 or Miniconda3. E.g., 

`conda install pandas`

2. You can just install the packages using pip. E.g., 

`pip3 install pandas`

You might need to install Anaconda or pip3 if you don't already have them installed.

It's also possible that you have one or more of the dependencies installed for python2, but not python3. So if that's the case make sure all the dependencies are installed for python3.

Finally, there are a lot of gaps in the alignment, and when I ran it on your file with that many gaps the script didn't work correctly.

Try using the nremover.pl script in this repository: https://github.com/tkchafin/scripts.git

That script will allow you to pre-filter the alignment based on proportions of missing data (per site and per individual), gaps, etc. Try filtering out sites with >50% gaps, for example. it seemed to work better when I ran it through nremover.pl first.

**Comment by btmartin721** [comment]
Hi. Were you able to use the script? If so, was it the dependencies?

**Comment by tommydevitt** [comment]
Yes, I finally managed to get it to run. It was the dependencies. Thanks for your help. A very useful script.

Tom

**Comment by btmartin721** [comment]
Cool. Glad I could help.
